# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e0889d18ea815f5dc8ef91caa5c5e2878136626780e4b34442bc97fb206826674eae1cfc75547d1f69423ad16005983bac4548c44a2f20b8c7cd720c92be4a7

test:
  secret_key_base: 4a951972ae8e52248a3f47b23bd61a995fe54bef0969a774f62f89c4c8daa9abe4c9fea5a4a021b44e9e70859eb1c909cf03248e33ab34b814ec388675a9770d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
